name: Lint
description: Run linting for the package

runs:
  using: composite
  steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Run linting
      shell: bash
      run: pnpm lint
